-- TABLE: Profiles
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  avatar_url TEXT,
  total_ects INTEGER DEFAULT 0,
  completed_modules INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- TABLE: Courses (Catalog Index)
CREATE TABLE courses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  level TEXT NOT NULL,
  subject TEXT NOT NULL,
  ects INTEGER DEFAULT 3,
  popularity INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- TABLE: User Progress
CREATE TABLE user_progress (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  course_id BIGINT REFERENCES courses(id) ON DELETE CASCADE,
  completed_sections TEXT[] DEFAULT '{}',
  is_finished BOOLEAN DEFAULT false,
  last_accessed TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- TABLE: Search Index (For Keywords)
CREATE TABLE search_index (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id BIGINT REFERENCES courses(id) ON DELETE CASCADE,
  keyword TEXT NOT NULL,
  weight INTEGER DEFAULT 1
);

-- FUNCTION: Update Global Stats
-- (On pourrait utiliser une vue matérialisée pour plus de perfs)
CREATE VIEW site_stats AS
SELECT 
  (SELECT COUNT(*) FROM profiles) as total_students,
  (SELECT COUNT(*) FROM courses WHERE is_active = true) as active_curricula,
  (SELECT SUM(popularity) FROM courses) as total_course_visits;
