const fs = require('fs');
const path = require('path');

const newTranslations = {
  en: {
    "Name": "Name",
    "Academic Level": "Academic Level",
    "Description": "Description",
    "Target Subject Fields": "Target Subject Fields",
    "Unvalidated Draft": "Unvalidated Draft",
    "This version is currently a draft. To validate and propagate (name, description, and visual keys), click 'Validate Version'. To discard, click 'Restore Original'.": "This version is currently a draft. To validate and propagate (name, description, and visual keys), click 'Validate Version'. To discard, click 'Restore Original'.",
    "Restore Original": "Restore Original",
    "Validate Version": "Validate Version",
    "Warning: Ephemeral Draft Preview": "Warning: Ephemeral Draft Preview",
    "Submitting a prompt will generate a new version of the widget, which must then be approved or rejected. Once approved, the previous version is overwritten and modifications are immediately propagated to the entire site. Handle with care.": "Submitting a prompt will generate a new version of the widget, which must then be approved or rejected. Once approved, the previous version is overwritten and modifications are immediately propagated to the entire site. Handle with care.",
    "Modifying the display name does not alter the technical component ID ({id}), which remains fixed for system stability. Enter between 3 and 50 characters.": "Modifying the display name does not alter the technical component ID ({id}), which remains fixed for system stability. Enter between 3 and 50 characters.",
    "Display name must be between 3 and 50 characters. It will automatically compile the technical component PascalCase ID.": "Display name must be between 3 and 50 characters. It will automatically compile the technical component PascalCase ID.",
    "Select academic levels...": "Select academic levels...",
    "Confirm Promotion & Validation?": "Confirm Promotion & Validation?",
    "Are you sure you want to validate this version? These changes will be applied instantly across the entire site. Once validated, there is no possibility of rollback or undo.": "Are you sure you want to validate this version? These changes will be applied instantly across the entire site. Once validated, there is no possibility of rollback or undo.",
    "Confirm Validation": "Confirm Validation",
    "Failed to force unlock widget.": "Failed to force unlock widget.",
    "Failed to update parameters": "Failed to update parameters",
    "Network exception saving parameters.": "Network exception saving parameters.",
    "Fullscreen Sandbox": "Fullscreen Sandbox",
    "Preset:": "Preset:",
    "{adminId} is currently editing this component": "{adminId} is currently editing this component",
    "Parameter saves or AI prompt commits are locked. Read-only preview available.": "Parameter saves or AI prompt commits are locked. Read-only preview available.",
    "Source code copied to clipboard!": "Source code copied to clipboard!",
    "Copied!": "Copied!",
    "Copy": "Copy",
    "Draft discarded and original widget version restored!": "Draft discarded and original widget version restored!",
    "Failed to restore original widget.": "Failed to restore original widget.",
    "Error restoring original widget.": "Error restoring original widget.",
    "Widget draft successfully promoted and validated! All translations updated.": "Widget draft successfully promoted and validated! All translations updated.",
    "Failed to validate widget.": "Failed to validate widget.",
    "Error validating widget draft.": "Error validating widget draft.",
    "{count} subjects selected": "{count} subjects selected"
  },
  fr: {
    "Name": "Nom",
    "Academic Level": "Niveau académique",
    "Description": "Description",
    "Target Subject Fields": "Domaines d'études cibles",
    "Unvalidated Draft": "Brouillon non validé",
    "This version is currently a draft. To validate and propagate (name, description, and visual keys), click 'Validate Version'. To discard, click 'Restore Original'.": "Cette version du widget est actuellement un brouillon. Pour valider et propager (nom, description et clés visuelles), cliquez sur « Valider la version ». Pour annuler, cliquez sur « Restaurer l'original ».",
    "Restore Original": "Restaurer l'original",
    "Validate Version": "Valider la version",
    "Warning: Ephemeral Draft Preview": "Attention : Aperçu brouillon éphémère",
    "Submitting a prompt will generate a new version of the widget, which must then be approved or rejected. Once approved, the previous version is overwritten and modifications are immediately propagated to the entire site. Handle with care.": "Soumettre une consigne générera une nouvelle version du widget, qui devra être approuvée ou rejetée. Une fois approuvée, la version précédente est écrasée et les modifications sont immédiatement propagées à l'ensemble du site. À manipuler avec précaution.",
    "Modifying the display name does not alter the technical component ID ({id}), which remains fixed for system stability. Enter between 3 and 50 characters.": "Note : Modifier le nom d'affichage n'altère pas l'identifiant technique du composant ({id}), qui reste fixe pour la stabilité du système. Saisissez entre 3 et 50 caractères.",
    "Display name must be between 3 and 50 characters. It will automatically compile the technical component PascalCase ID.": "Le nom d'affichage doit contenir entre 3 et 50 caractères. Il sera utilisé pour déduire l'ID PascalCase technique du composant.",
    "Select academic levels...": "Sélectionnez les niveaux...",
    "Confirm Promotion & Validation?": "Confirmer la validation ?",
    "Are you sure you want to validate this version? These changes will be applied instantly across the entire site. Once validated, there is no possibility of rollback or undo.": "Êtes-vous sûr de vouloir valider cette version ? Les modifications seront appliquées instantanément sur l'ensemble du site. Une fois validé, il ne sera plus possible d'annuler ou de revenir en arrière.",
    "Confirm Validation": "Confirmer la validation",
    "Failed to force unlock widget.": "Échec du déverrouillage forcé du widget.",
    "Failed to update parameters": "Échec de la mise à jour des paramètres",
    "Network exception saving parameters.": "Exception réseau lors de l'enregistrement des paramètres.",
    "Fullscreen Sandbox": "Bac à sable plein écran",
    "Preset:": "Préréglage :",
    "{adminId} is currently editing this component": "{adminId} est en train de modifier ce composant",
    "Parameter saves or AI prompt commits are locked. Read-only preview available.": "Les sauvegardes de paramètres et les validations de prompts IA sont verrouillées. Aperçu en lecture seule disponible.",
    "Source code copied to clipboard!": "Code source copié dans le presse-papiers !",
    "Copied!": "Copié !",
    "Copy": "Copier",
    "Draft discarded and original widget version restored!": "Brouillon rejeté et version originale du widget restaurée !",
    "Failed to restore original widget.": "Échec de la restauration du widget original.",
    "Error restoring original widget.": "Erreur lors de la restauration du widget original.",
    "Widget draft successfully promoted and validated! All translations updated.": "Brouillon du widget promu et validé avec succès ! Toutes les traductions ont été mises à jour.",
    "Failed to validate widget.": "Échec de la validation du widget.",
    "Error validating widget draft.": "Erreur lors de la validation du brouillon du widget.",
    "{count} subjects selected": "{count} disciplines sélectionnées"
  },
  es: {
    "Name": "Nombre",
    "Academic Level": "Nivel académico",
    "Description": "Descripción",
    "Target Subject Fields": "Campos de asignaturas de destino",
    "Unvalidated Draft": "Borrador no validado",
    "This version is currently a draft. To validate and propagate (name, description, and visual keys), click 'Validate Version'. To discard, click 'Restore Original'.": "Esta versión es actualmente un borrador. Para validar y propagar (nombre, descripción y claves visuales), haga clic en 'Validar versión'. Para descartar, haga clic en 'Restaurar original'.",
    "Restore Original": "Restaurar original",
    "Validate Version": "Validar versión",
    "Warning: Ephemeral Draft Preview": "Advertencia: Vista previa de borrador efímero",
    "Submitting a prompt will generate a new version of the widget, which must then be approved or rejected. Once approved, the previous version is overwritten and modifications are immediately propagated to the entire site. Handle with care.": "Enviar un prompt generará una nueva versión del widget, que luego debe ser aprobada o rechazada. Once aprobada, la versión anterior se sobrescribe y las modificaciones se propagan inmediatamente a todo el sitio. Manipular con cuidado.",
    "Modifying the display name does not alter the technical component ID ({id}), which remains fixed for system stability. Enter between 3 and 50 characters.": "Nota: Modificar el nombre de visualización no altera el ID técnico del componente ({id}), que permanece fijo para la estabilidad del sistema. Introduzca entre 3 y 50 caracteres.",
    "Display name must be between 3 and 50 characters. It will automatically compile the technical component PascalCase ID.": "El nombre de visualización debe tener entre 3 y 50 caracteres. Compilará automáticamente el ID técnico de PascalCase del componente.",
    "Select academic levels...": "Seleccionar niveles académicos...",
    "Confirm Promotion & Validation?": "¿Confirmar la validación?",
    "Are you sure you want to validate this version? These changes will be applied instantly across the entire site. Once validated, there is no possibility of rollback or undo.": "¿Está seguro de que desea validar esta versión? Los cambios se aplicarán instantáneamente en todo el sitio. Una vez validada, no habrá posibilidad de deshacer o revertir.",
    "Confirm Validation": "Confirmar validación",
    "Failed to force unlock widget.": "Error al forzar el desbloqueo del widget.",
    "Failed to update parameters": "Error al actualizar los parámetros",
    "Network exception saving parameters.": "Excepción de red al guardar los parámetros.",
    "Fullscreen Sandbox": "Espacio de trabajo a pantalla completa",
    "Preset:": "Preajuste:",
    "{adminId} is currently editing this component": "{adminId} está editando actualmente este componente",
    "Parameter saves or AI prompt commits are locked. Read-only preview available.": "El guardado de parámetros y los envíos de prompts de IA están bloqueados. Vista previa de solo lectura disponible.",
    "Source code copied to clipboard!": "¡Código fuente copiado al portapapeles!",
    "Copied!": "¡Copiado!",
    "Copy": "Copiar",
    "Draft discarded and original widget version restored!": "¡Borrador descartado y versión original del widget restaurada!",
    "Failed to restore original widget.": "Error al restaurar el widget original.",
    "Error restoring original widget.": "Error al restaurar el widget original.",
    "Widget draft successfully promoted and validated! All translations updated.": "¡Borrador del widget promocionado y validado con éxito! Todas las traducciones actualizadas.",
    "Failed to validate widget.": "Error al validar el widget.",
    "Error validating widget draft.": "Error al validar el borrador del widget.",
    "{count} subjects selected": "{count} temas seleccionados"
  },
  de: {
    "Name": "Name",
    "Academic Level": "Akademisches Niveau",
    "Description": "Beschreibung",
    "Target Subject Fields": "Ziel-Fachgebiete",
    "Unvalidated Draft": "Nicht validierter Entwurf",
    "This version is currently a draft. To validate and propagate (name, description, and visual keys), click 'Validate Version'. To discard, click 'Restore Original'.": "Diese Version ist derzeit ein Entwurf. Um zu validieren und zu verbreiten (Name, Beschreibung und visuelle Tasten), klicken Sie auf 'Version validieren'. Zum Verwerfen klicken Sie auf 'Original wiederherstellen'.",
    "Restore Original": "Original wiederherstellen",
    "Validate Version": "Version validieren",
    "Warning: Ephemeral Draft Preview": "Warnung: Flüchtige Entwurfsanschauung",
    "Submitting a prompt will generate a new version of the widget, which must then be approved or rejected. Once approved, the previous version is overwritten and modifications are immediately propagated to the entire site. Mit Vorsicht behandeln.": "Die Übermittlung eines Prompts generiert eine neue Version des Widgets, die dann genehmigt oder abgelehnt werden muss. Nach der Genehmigung wird die vorherige Version überschrieben und die Änderungen werden sofort auf die gesamte Website übertragen. Mit Vorsicht behandeln.",
    "Modifying the display name does not alter the technical component ID ({id}), which remains fixed for system stability. Enter between 3 and 50 characters.": "Hinweis: Das Ändern des Anzeigenamens ändert nicht die technische Komponenten-ID ({id}), die für die Systemstabilität fest bleibt. Geben Sie zwischen 3 und 50 Zeichen ein.",
    "Display name must be between 3 and 50 characters. It will automatically compile the technical component PascalCase ID.": "Der Anzeigename muss zwischen 3 und 50 Zeichen lang sein. Er kompiliert automatisch die technische Komponenten-PascalCase-ID.",
    "Select academic levels...": "Akademische Niveaus auswählen...",
    "Confirm Promotion & Validation?": "Validierung bestätigen?",
    "Are you sure you want to validate this version? These changes will be applied instantly across the entire site. Once validated, there is no possibility of rollback or undo.": "Sind Sie sicher, dass Sie diese Version validieren möchten? Die Änderungen werden sofort auf der gesamten Website wirksam. Nach der Validierung gibt es keine Möglichkeit eines Rollbacks oder Rückgängigmachens.",
    "Confirm Validation": "Validierung bestätigen",
    "Failed to force unlock widget.": "Erzwungenes Entsperren des Widgets fehlgeschlagen.",
    "Failed to update parameters": "Fehler beim Aktualisieren der Parameter",
    "Network exception saving parameters.": "Netzwerkfehler beim Speichern der Parameter.",
    "Fullscreen Sandbox": "Vollbild-Sandbox",
    "Preset:": "Voreinstellung:",
    "{adminId} is currently editing this component": "{adminId} bearbeitet diese Komponente gerade",
    "Parameter saves or AI prompt commits are locked. Read-only preview available.": "Parameterspeicherungen oder KI-Prompt-Commits sind gesperrt. Nur-Lese-Vorschau verfügbar.",
    "Source code copied to clipboard!": "Quellcode in die Zwischenablage kopiert!",
    "Copied!": "Kopiert!",
    "Copy": "Kopieren",
    "Draft discarded and original widget version restored!": "Entwurf verworfen und ursprüngliche Widget-Version wiederhergestellt!",
    "Failed to restore original widget.": "Wiederherstellung des ursprünglichen Widgets fehlgeschlagen.",
    "Error restoring original widget.": "Fehler beim Wiederherstellen des ursprünglichen Widgets.",
    "Widget draft successfully promoted and validated! All translations updated.": "Widget-Entwurf erfolgreich hochgestuft und validiert! Alle Übersetzungen aktualisiert.",
    "Failed to validate widget.": "Validierung des Widgets fehlgeschlagen.",
    "Error validating widget draft.": "Fehler bei der Validierung des Widget-Entwurfs.",
    "{count} subjects selected": "{count} Themen ausgewählt"
  },
  zh: {
    "Name": "名称",
    "Academic Level": "学术水平",
    "Description": "描述",
    "Target Subject Fields": "目标学科领域",
    "Unvalidated Draft": "未经验证的草稿",
    "This version is currently a draft. To validate and propagate (name, description, and visual keys), click 'Validate Version'. To discard, click 'Restore Original'.": "此版本当前为草稿。要验证并发布（名称、描述和视觉键），请单击“验证版本”。要放弃，请单击“还原原始版本”。",
    "Restore Original": "还原原始版本",
    "Validate Version": "验证版本",
    "Warning: Ephemeral Draft Preview": "警告：临时草稿预览",
    "Submitting a prompt will generate a new version of the widget, which must then be approved or rejected. Once approved, the previous version is overwritten and modifications are immediately propagated to the entire site. 请谨慎操作。": "提交提示语将生成新版本的组件，该版本必须经过批准或拒绝。一旦获得批准，前一版本将被覆盖，且修改会立即应用到整个网站。请谨慎操作。",
    "Modifying the display name does not alter the technical component ID ({id}), which remains fixed for system stability. Enter between 3 and 50 characters.": "注意：修改显示名称不会更改技术组件ID（{id}），该ID保持固定以维持系统稳定性。请输入3到50个字符。",
    "Display name must be between 3 and 50 characters. It will automatically compile the technical component PascalCase ID.": "显示名称必须在3到50个字符之间。它将自动编译技术组件的PascalCase ID。",
    "Select academic levels...": "选择学术水平...",
    "Confirm Promotion & Validation?": "确认验证？",
    "Are you sure you want to validate this version? These changes will be applied instantly across the entire site. Once validated, there is no possibility of rollback or undo.": "您确定要验证此版本吗？更改将立即应用到整个网站。一旦验证，将无法撤销或恢复。",
    "Confirm Validation": "确认验证",
    "Failed to force unlock widget.": "强制解锁组件失败。",
    "Failed to update parameters": "更新参数失败",
    "Network exception saving parameters.": "保存参数时网络异常。",
    "Fullscreen Sandbox": "全屏沙盒",
    "Preset:": "预设：",
    "{adminId} is currently editing this component": "{adminId} 当前正在编辑此组件",
    "Parameter saves or AI prompt commits are locked. Read-only preview available.": "参数保存或人工智能提示语提交已被锁定。仅提供只读预览。",
    "Source code copied to clipboard!": "源代码已复制到剪贴板！",
    "Copied!": "已复制！",
    "Copy": "复制",
    "Draft discarded and original widget version restored!": "已放弃草稿并还原了原始组件版本！",
    "Failed to restore original widget.": "无法还原原始组件。",
    "Error restoring original widget.": "还原原始组件时出错。",
    "Widget draft successfully promoted and validated! All translations updated.": "组件草稿成功发布并验证！所有翻译均已更新。",
    "Failed to validate widget.": "组件验证失败。",
    "Error validating widget draft.": "验证组件草稿时出错。",
    "{count} subjects selected": "已选择 {count} 个学科"
  },
  pt: {
    "Name": "Nome",
    "Academic Level": "Nível Acadêmico",
    "Description": "Descrição",
    "Target Subject Fields": "Campos de Disciplinas de Destino",
    "Unvalidated Draft": "Rascunho não validado",
    "This version is currently a draft. To validate and propagate (name, description, and visual keys), click 'Validate Version'. To discard, click 'Restore Original'.": "Esta versão é atualmente um rascunho. Para validar e propagar (nome, descrição e chaves visuais), clique em 'Validar versão'. Para descartar, clique em 'Restaurar original'.",
    "Restore Original": "Restaurar original",
    "Validate Version": "Validar versão",
    "Warning: Ephemeral Draft Preview": "Aviso: Visualização temporária do rascunho",
    "Submitting a prompt will generate a new version of the widget, which must then be approved or rejected. Once approved, the previous version is overwritten and modifications are immediately propagated to the entire site. Handle with care.": "Enviar um comando gerará uma nova versão do widget, que deve ser aprovada ou rejeitada. Uma vez aprovada, a versão anterior é substituída e as modificações são propagadas imediatamente para todo o site. Manuseie com cuidado.",
    "Modifying the display name does not alter the technical component ID ({id}), which remains fixed for system stability. Enter between 3 and 50 characters.": "Nota: Modificar o nome de exibição não altera o ID técnico do componente ({id}), que permanece fixo para estabilidade do sistema. Insira entre 3 e 50 caracteres.",
    "Display name must be between 3 and 50 characters. It will automatically compile the technical component PascalCase ID.": "O nome de exibição deve ter entre 3 e 50 caracteres. Ele compilará automaticamente o ID PascalCase técnico do componente.",
    "Select academic levels...": "Selecionar níveis acadêmicos...",
    "Confirm Promotion & Validation?": "Confirmar validação?",
    "Are you sure you want to validate this version? These changes will be applied instantly across the entire site. Once validated, there is no possibility of rollback or undo.": "Tem certeza de que deseja validar esta versão? As alterações serão aplicadas instantaneamente em todo o site. Uma vez validada, não haverá possibilidade de desfazer ou reverter.",
    "Confirm Validation": "Confirmar validação",
    "Failed to force unlock widget.": "Falha ao forçar o desbloqueio do widget.",
    "Failed to update parameters": "Falha ao atualizar parâmetros",
    "Network exception saving parameters.": "Exceção de rede ao salvar os parâmetros.",
    "Fullscreen Sandbox": "Sandbox em tela cheia",
    "Preset:": "Predefinição:",
    "{adminId} is currently editing this component": "{adminId} está editando este componente atualmente",
    "Parameter saves or AI prompt commits are locked. Read-only preview available.": "O salvamento de parâmetros ou envios de comandos de IA estão bloqueados. Visualização apenas para leitura disponível.",
    "Source code copied to clipboard!": "Código-fonte copiado para a área de transferência!",
    "Copied!": "Copiado!",
    "Copy": "Copiar",
    "Draft discarded and original widget version restored!": "Rascunho descartado e versão original do widget restaurada!",
    "Failed to restore original widget.": "Falha ao restaurar o widget original.",
    "Error restoring original widget.": "Erro ao restaurar o widget original.",
    "Widget draft successfully promoted and validated! All translations updated.": "Rascunho do widget promovido e validado com sucesso! Todas as traduções atualizadas.",
    "Failed to validate widget.": "Falha ao validar o widget.",
    "Error validating widget draft.": "Erro ao validar o rascunho do widget.",
    "{count} subjects selected": "{count} assuntos selecionados"
  },
  ar: {
    "Name": "الاسم",
    "Academic Level": "المستوى الأكاديمي",
    "Description": "الوصف",
    "Target Subject Fields": "مجالات المواد المستهدفة",
    "Unvalidated Draft": "مسودة غير مؤكدة",
    "This version is currently a draft. To validate and propagate (name, description, and visual keys), click 'Validate Version'. To discard, click 'Restore Original'.": "هذا الإصدار مسودة حاليًا. للتحقق من صحته ونشره (الاسم والوصف والمفاتيح المرئية)، انقر فوق 'تأكيد النسخة'. للتجاهل، انقر فوق 'استعادة الأصلي'.",
    "Restore Original": "استعادة الأصلي",
    "Validate Version": "تأكيد النسخة",
    "Warning: Ephemeral Draft Preview": "تحذير: معاينة مسودة مؤقتة",
    "Submitting a prompt will generate a new version of the widget, which must then be approved or rejected. Once approved, the previous version is overwritten and modifications are immediately propagated to the entire site. Handle with care.": "سيؤدي إرسال موجه إلى إنشاء نسخة جديدة من الأداة، والتي يجب بعد ذلك الموافقة عليها أو رفضها. بمجرد الموافقة عليها، يتم الكتابة فوق النسخة السابقة ويتم نشر التعديلات فورًا في الموقع بأكمله. تعامل معها بحذر.",
    "Modifying the display name does not alter the technical component ID ({id}), which remains fixed for system stability. Enter between 3 and 50 characters.": "ملاحظة: تعديل اسم العرض لا يغير معرّف المكون الفني ({id})، والذي يظل ثابتًا لاستقرار النظام. أدخل ما بين 3 و 50 حرفًا.",
    "Display name must be between 3 and 50 characters. It will automatically compile the technical component PascalCase ID.": "يجب أن يتراوح اسم العرض بين 3 و 50 حرفًا. سيقوم تلقائيًا بتجميع معرّف PascalCase الفني للمكون.",
    "Select academic levels...": "حدد المستويات الأكاديمية...",
    "Confirm Promotion & Validation?": "تأكيد التحقق من الصحة؟",
    "Are you sure you want to validate this version? These changes will be applied instantly across the entire site. Once validated, there is no possibility of rollback or undo.": "هل أنت متأكد من أنك تريد التحقق من صحة هذا الإصدار؟ سيتم تطبيق التغييرات فورًا على الموقع بأكمله. بمجرد التحقق من صحتها، لن يكون هناك أي احتمال للتراجع أو الإلغاء.",
    "Confirm Validation": "تأكيد التحقق من الصحة",
    "Failed to force unlock widget.": "فشل في فرض فتح الأداة.",
    "Failed to update parameters": "فشل في تحديث المعلمات",
    "Network exception saving parameters.": "استثناء الشبكة أثناء حفظ المعلمات.",
    "Fullscreen Sandbox": "بيئة عمل شاشة كاملة",
    "Preset:": "المسبق:",
    "{adminId} is currently editing this component": "{adminId} يقوم حاليًا بتعديل هذا المكون",
    "Parameter saves or AI prompt commits are locked. Read-only preview available.": "تم قفل عمليات حفظ المعلمات أو التزامات موجه الذكاء الاصطناعي. تتوفر معاينة للقراءة فقط.",
    "Source code copied to clipboard!": "تم نسخ الكود المصدري إلى الحافظة!",
    "Copied!": "تم النسخ!",
    "Copy": "نسخ",
    "Draft discarded and original widget version restored!": "تم تجاهل المسودة واستعادة نسخة الأداة الأصلية!",
    "Failed to restore original widget.": "فشل في استعادة الأداة الأصلية.",
    "Error restoring original widget.": "خطأ في استعادة الأداة الأصلية.",
    "Widget draft successfully promoted and validated! All translations updated.": "تم ترويج مسودة الأداة والتحقق من صحتها بنجاح! تم تحديث جميع التراجم.",
    "Failed to validate widget.": "فشل في التحقق من صحة الأداة.",
    "Error validating widget draft.": "خطأ في التحقق من صحة مسودة الأداة.",
    "{count} subjects selected": "تم تحديد {count} موضوعًا"
  },
  hi: {
    "Name": "नाम",
    "Academic Level": "शैक्षणिक स्तर",
    "Description": "विवरण",
    "Target Subject Fields": "लक्ष्य विषय क्षेत्र",
    "Unvalidated Draft": "अपुष्टीकृत प्रारूप",
    "This version is currently a draft. To validate and propagate (name, description, and visual keys), click 'Validate Version'. To discard, click 'Restore Original'.": "यह संस्करण वर्तमान में एक प्रारूप है। सत्यापित और प्रसारित करने के लिए (नाम, विवरण और दृश्य कुंजी), 'संस्करण सत्यापित करें' पर क्लिक करें। खारिज करने के लिए, 'मूल पुनर्स्थापित करें' पर क्लिक करें।",
    "Restore Original": "मूल पुनर्स्थापित करें",
    "Validate Version": "संस्करण सत्यापित करें",
    "Warning: Ephemeral Draft Preview": "चेतावनी: क्षणिक प्रारूप पूर्वावलोकन",
    "Submitting a prompt will generate a new version of the widget, which must then be approved or rejected. Once approved, the previous version is overwritten and modifications are immediately propagated to the entire site. Handle with care.": "प्रॉम्प्ट सबमिट करने से विजेट का एक नया संस्करण तैयार होगा, जिसे बाद में स्वीकृत या अस्वीकृत किया जाना चाहिए। एक बार स्वीकृत होने के बाद, पिछला संस्करण अधिलेखित हो जाता है और संशोधन तुरंत पूरी साइट पर प्रसारित हो जाते हैं। सावधानी से संभालें।",
    "Modifying the display name does not alter the technical component ID ({id}), which remains fixed for system stability. Enter between 3 and 50 characters.": "ध्यान दें: प्रदर्शन नाम बदलने से तकनीकी घटक आईडी ({id}) में कोई बदलाव नहीं होता है, जो सिस्टम की स्थिरता के लिए स्थिर रहता है। 3 से 50 वर्णों के बीच दर्ज करें।",
    "Display name must be between 3 and 50 characters. It will automatically compile the technical component PascalCase ID.": "प्रदर्शन नाम 3 और 50 वर्णों के बीच होना चाहिए। यह स्वचालित रूप से तकनीकी घटक पास्कलकेस (PascalCase) आईडी संकलित करेगा।",
    "Select academic levels...": "शैक्षणिक स्तर चुनें...",
    "Confirm Promotion & Validation?": "सत्यापन की पुष्टि करें?",
    "Are you sure you want to validate this version? These changes will be applied instantly across the entire site. Once validated, there is no possibility of rollback or undo.": "क्या आप वाकई इस संस्करण को सत्यापित करना चाहते हैं? ये परिवर्तन तुरंत पूरी साइट पर लागू हो जाएंगे। एक बार सत्यापित होने के बाद, वापस लौटने या पूर्ववत करने की कोई संभावना नहीं होगी।",
    "Confirm Validation": "सत्यापन की पुष्टि करें",
    "Failed to force unlock widget.": "विजेट को जबरन अनलॉक करने में विफल।",
    "Failed to update parameters": "पैरामीटर अपडेट करने में विफल",
    "Network exception saving parameters.": "पैरामीटर सहेजते समय नेटवर्क अपवाद।",
    "Fullscreen Sandbox": "पूर्ण स्क्रीन सैंडबॉक्स",
    "Preset:": "प्रिसेट:",
    "{adminId} is currently editing this component": "{adminId} वर्तमान में इस घटक को संपादित कर रहा है",
    "Parameter saves or AI prompt commits are locked. Read-only preview available.": "पैरामीटर सेव या एआई प्रॉम्प्ट कमिट लॉक हैं। केवल पढ़ने के लिए पूर्वावलोकन उपलब्ध है।",
    "Source code copied to clipboard!": "स्रोत कोड क्लिपबोर्ड पर कॉपी किया गया!",
    "Copied!": "कॉपी किया गया!",
    "Copy": "कॉपी",
    "Draft discarded and original widget version restored!": "प्रारूप खारिज कर दिया गया और मूल विजेट संस्करण बहाल कर दिया गया!",
    "Failed to restore original widget.": "मूल विजेट को पुनर्स्थापित करने में विफल।",
    "Error restoring original widget.": "मूल विजेट को पुनर्स्थापित करने में त्रुटि।",
    "Widget draft successfully promoted and validated! All translations updated.": "विजेट प्रारूप को सफलतापूर्वक बढ़ावा दिया गया और सत्यापित किया गया! सभी अनुवाद अपडेट किए गए।",
    "Failed to validate widget.": "विजेट को सत्यापित करने में विफल।",
    "Error validating widget draft.": "विजेट प्रारूप को सत्यापित करने में त्रुटि।",
    "{count} subjects selected": "{count} विषय चुने गए"
  },
  ur: {
    "Name": "نام",
    "Academic Level": "تعلیمی سطح",
    "Description": "تفصیل",
    "Target Subject Fields": "ہدف کے مضامین",
    "Unvalidated Draft": "غیر توثیق شدہ مسودہ",
    "This version is currently a draft. To validate and propagate (name, description, and visual keys), click 'Validate Version'. To discard, click 'Restore Original'.": "یہ ورژن فی الحال ایک مسودہ ہے۔ توثیق کرنے اور آگے بڑھانے کے لیے (نام، تفصیل اور بصری کیز)، 'ورژن کی توثیق کریں' پر کلک کریں۔ مسترد کرنے کے لیے، 'اصل بحال کریں' پر کلک کریں۔",
    "Restore Original": "اصل بحال کریں",
    "Validate Version": "ورژن کی توثیق کریں",
    "Warning: Ephemeral Draft Preview": "انتباہ: عارضی مسودہ کا جائزہ",
    "Submitting a prompt will generate a new version of the widget, which must then be approved or rejected. Once approved, the previous version is overwritten and modifications are immediately propagated to the entire site. Handle with care.": "پرامپٹ جمع کرانے سے وزٹ کا ایک نیا ورژن تیار ہو گا، جس کی بعد میں منظوری یا مسترد ہونا ضروری ہے۔ ایک بار منظور ہونے کے بعد، پچھلا ورژن اوور رائٹ ہو جاتا ہے اور ترمیمات فوری طور پر پوری سائٹ پر نافذ ہو جاتی ہیں۔ احتیاط سے کام لیں۔",
    "Modifying the display name does not alter the technical component ID ({id}), which remains fixed for system stability. Enter between 3 and 50 characters.": "نوٹ: ڈسپلے کا نام تبدیل کرنے سے تکنیکی جزو کی ID ({id}) تبدیل نہیں ہوتی ہے، جو سسٹم کے استحکام کے لیے برقرار رہتی ہے۔ 3 اور 50 حروف کے درمیان درج کریں۔",
    "Display name must be between 3 and 50 characters. It will automatically compile the technical component PascalCase ID.": "ڈسپلے کا نام 3 اور 50 حروف کے درمیان ہونا چاہیے۔ یہ خود بخود تکنیکی جزو PascalCase ID کو مرتب کرے گا۔",
    "Select academic levels...": "تعلیمی سطح منتخب کریں...",
    "Confirm Promotion & Validation?": "توثیق کی تصدیق کریں؟",
    "Are you sure you want to validate this version? These changes will be applied instantly across the entire site. Once validated, there is no possibility of rollback or undo.": "کیا آپ واقعی اس ورژن کی توثیق کرنا چاہتے ہیں؟ یہ تبدیلیاں فوری طور پر پوری سائٹ پر لاگو ہو جائیں گی۔ ایک بار توثیق ہو جانے کے بعد، واپس جانے یا کالعدم کرنے کا کوئی امکان نہیں ہو گا۔",
    "Confirm Validation": "توثیق کی تصدیق کریں",
    "Failed to force unlock widget.": "وزٹ کو زبردستی انلاک کرنے میں ناکام۔",
    "Failed to update parameters": "پیرامیٹرز کو اپ ڈیٹ کرنے میں ناکام",
    "Network exception saving parameters.": "پیرامیٹرز کو محفوظ کرتے وقت نیٹ ورک کی خرابی۔",
    "Fullscreen Sandbox": "فل سکرین سینڈ باکس",
    "Preset:": "پری سیٹ:",
    "{adminId} is currently editing this component": "{adminId} فی الحال اس جزو میں ترمیم کر رہا ہے",
    "Parameter saves or AI prompt commits are locked. Read-only preview available.": "پیرامیٹر محفوظ کرنا یا AI پرامپٹ کی منتقلی مقفل ہے۔ صرف پڑھنے کا جائزہ دستیاب ہے۔",
    "Source code copied to clipboard!": "سورس کوڈ کلپ بورڈ پر کاپی ہو گیا! ",
    "Copied!": "کاپی ہو گیا!",
    "Copy": "کاپی",
    "Draft discarded and original widget version restored!": "مسودہ مسترد کر دیا گیا اور اصل وزٹ ورژن بحال کر دیا گیا!",
    "Failed to restore original widget.": "اصل وزٹ بحال کرنے میں ناکام۔ ",
    "Error restoring original widget.": "اصل وزٹ بحال کرنے میں خرابی۔ ",
    "Widget draft successfully promoted and validated! All translations updated.": "وزٹ مسودہ کامیابی کے ساتھ فروغ دیا گیا اور اس کی توثیق کی گئی! تمام تراجم اپ ڈیٹ ہو گئے۔",
    "Failed to validate widget.": "وزٹ کی توثیق کرنے میں ناکام۔",
    "Error validating widget draft.": "اورجن مسودہ کی توثیق کرنے میں خرابی۔",
    "{count} subjects selected": "{count} مضامین منتخب کیے گئے"
  }
};

for (const lang of Object.keys(newTranslations)) {
  const filePath = path.join(__dirname, `../src/app/admin/curriculum/locales/${lang}.ts`);
  if (!fs.existsSync(filePath)) {
    console.error(`File not found: ${filePath}`);
    continue;
  }
  let content = fs.readFileSync(filePath, 'utf8');
  
  // Find the object content
  const startIdx = content.indexOf('{');
  const endIdx = content.lastIndexOf('}');
  if (startIdx === -1 || endIdx === -1) {
    console.error(`Could not parse brackets in ${lang}.ts`);
    continue;
  }
  
  const body = content.substring(startIdx + 1, endIdx);
  let parsedObj;
  try {
    parsedObj = eval('({' + body + '})');
  } catch (e) {
    console.error(`Failed to eval body of ${lang}.ts`, e);
    continue;
  }
  
  // Merge new translations
  const merged = { ...parsedObj, ...newTranslations[lang] };
  
  // Format the merged object back to a nice string
  const lines = Object.entries(merged).map(([key, val]) => {
    const escapedKey = JSON.stringify(key);
    const escapedVal = JSON.stringify(val);
    return `  ${escapedKey}: ${escapedVal},`;
  });
  
  const newContent = `export const locale: Record<string, string> = {\n${lines.join('\n')}\n};\n`;
  fs.writeFileSync(filePath, newContent, 'utf8');
  console.log(`Successfully updated ${lang}.ts`);
}
