"use client";

import React, { useState, useEffect, useRef } from 'react';
import { Play, Pause, RotateCcw, Activity, Info, Sliders, Layers } from 'lucide-react';

interface SimulationPreset {
  id: string;
  name: string;
  description: string;
  stages: {
    at: number; // percentage threshold
    label: string;
    details: string;
  }[];
}

const PRESETS: SimulationPreset[] = [
  {
    id: "mitosis",
    name: "Cell Mitosis Division",
    description: "Watch a eukaryotic cell duplicate its chromosomes and divide into two identical daughter cells.",
    stages: [
      { at: 0, label: "Interphase", details: "The cell is in its resting state. DNA is replicated but exists as uncoiled chromatin threads inside an intact nucleus." },
      { at: 25, label: "Prophase", details: "Chromatin condenses into thick visible chromosomes. The nuclear envelope disintegrates, and spindle fibers begin to form from opposing poles." },
      { at: 50, label: "Metaphase", details: "Spindle fibers align the sister chromatids perfectly along the equatorial center plate (metaphase plate)." },
      { at: 75, label: "Anaphase", details: "Spindle fibers shorten, pulling sister chromatids apart to opposite poles of the cell. The cell membrane begins to constrict (cleavage furrow)." },
      { at: 100, label: "Telophase & Cytokinesis", details: "Nuclear membranes reform around the separated chromosome groups. The cytoplasm pinches completely, splitting into two distinct diploid cells." }
    ]
  },
  {
    id: "carnot",
    name: "Carnot Thermodynamic Cycle",
    description: "The ideal heat engine cycle defining the maximum efficiency limit of any thermodynamic system.",
    stages: [
      { at: 0, label: "1. Isothermal Expansion (A → B)", details: "Gas expands at a constant high temperature (Th). The cylinder is in contact with a hot reservoir. Piston moves upwards; volume increases, pressure drops." },
      { at: 25, label: "2. Adiabatic Expansion (B → C)", details: "The cylinder is thermally insulated. Gas continues to expand and do work. Volume increases further, pressure drops, and temperature falls to Tc." },
      { at: 50, label: "3. Isothermal Compression (C → D)", details: "Gas is compressed at a constant cold temperature (Tc) while in contact with a cold sink. Piston moves down; volume decreases, pressure rises, heat is rejected." },
      { at: 100, label: "4. Adiabatic Compression (D → A)", details: "The cylinder is insulated again. Compression continues, causing temperature to rise back to Th. Pressure increases, returning the system to its initial state." }
    ]
  },
  {
    id: "waves",
    name: "Wave Superposition & Speed",
    description: "Investigate mechanical wave travel. Alter frequency and speed to see constructive/destructive interference.",
    stages: [
      { at: 0, label: "Initial State", details: "Continuous coherent sine wave generated by an oscillator traveling along a medium." },
      { at: 50, label: "Medium Resistance", details: "Adjust frequency and amplitude sliders to see how wave speed (v = f * λ) remains constant unless the medium is altered." },
      { at: 100, label: "Boundary Reflection", details: "Constructive and destructive interference overlaps as waves reflect off boundaries." }
    ]
  },
  {
    id: "doubleslit",
    name: "Double-Slit Diffraction",
    description: "Thomas Young's experiment showing wave-particle duality and the wave nature of light through coherent interference.",
    stages: [
      { at: 0, label: "Wavefront Emission", details: "Coherent wave source emits planar wavefronts traveling towards a partition with two narrow slits." },
      { at: 50, label: "Slit Diffraction", details: "The two slits act as secondary sources of coherent spherical wavelets spreading out in all directions." },
      { at: 100, label: "Fringe Interference", details: "Overlapping wavelets interfere constructively (bright fringes) and destructively (dark fringes) forming a pattern on the detector screen." }
    ]
  },
  {
    id: "enzyme",
    name: "Enzyme-Substrate Mechanism",
    description: "The induced-fit biological model illustrating enzyme catalysis and metabolic split functions.",
    stages: [
      { at: 0, label: "Substrate Approach", details: "Substrate molecule floats towards the active site of the specific enzyme catalyst." },
      { at: 50, label: "Enzyme-Substrate Complex", details: "The substrate binds. The enzyme shifts its shape slightly (induced fit) to securely lock and destabilize molecular bonds." },
      { at: 100, label: "Product Release", details: "The chemical reaction is complete. The substrate splits into two smaller products, which are released. The enzyme returns to its original shape." }
    ]
  }
];

export const DynamicSimulation = ({ presetId = "mitosis" }: { presetId?: string }) => {
  const [activePreset, setActivePreset] = useState<SimulationPreset>(() => {
    return PRESETS.find(p => p.id === presetId) || PRESETS[0];
  });

  const [progress, setProgress] = useState(0); // 0 to 100 timeline scrubber
  const [isPlaying, setIsPlaying] = useState(false);
  const playRef = useRef<number | null>(null);

  // Extra simulation parameters
  const [freq, setFreq] = useState(1.5);        // For waves / double slit
  const [amp, setAmp] = useState(30);         // For waves
  const [wavelength, setWavelength] = useState(500); // Nanometers for double-slit color representation

  useEffect(() => {
    const found = PRESETS.find(p => p.id === presetId);
    if (found) {
      setActivePreset(found);
      setProgress(0);
      setIsPlaying(false);
    }
  }, [presetId]);

  // Handle play/pause looping
  useEffect(() => {
    if (isPlaying) {
      const step = () => {
        setProgress((prev) => {
          if (prev >= 100) {
            return 0; // Loop around
          }
          return prev + 0.35; // Fine step increment for smooth speed
        });
        playRef.current = requestAnimationFrame(step);
      };
      playRef.current = requestAnimationFrame(step);
    } else {
      if (playRef.current) cancelAnimationFrame(playRef.current);
    }

    return () => {
      if (playRef.current) cancelAnimationFrame(playRef.current);
    };
  }, [isPlaying]);

  // Find active step description
  const activeStage = React.useMemo(() => {
    let matched = activePreset.stages[0];
    activePreset.stages.forEach(s => {
      if (progress >= s.at) {
        matched = s;
      }
    });
    return matched;
  }, [progress, activePreset]);

  // Render SVG for Mitosis Cell Division
  const drawMitosis = () => {
    const p = progress / 100;
    
    // Coordinates for dual nucleus poles
    const poleLeftX = 150 - (p * 50);
    const poleRightX = 250 + (p * 50);
    
    // Cell shape pinching
    // Cleavage furrow: path constricts inside the center as p approaches 100%
    const centerPinch = p < 0.6 ? 0 : (p - 0.6) * 2.5; // constricts from 0 to 1
    const pathD = p < 0.6 
      ? "M 100 120 C 100 60, 300 60, 300 120 C 300 180, 100 180, 100 120 Z" // Oval
      : `M 100 120 C 100 65, 185 ${60 + (centerPinch*45)}, 200 ${120 - (centerPinch*25)} C 215 ${60 + (centerPinch*45)}, 300 65, 300 120 C 300 175, 215 ${180 - (centerPinch*45)}, 200 ${120 + (centerPinch*25)} C 185 ${180 - (centerPinch*45)}, 100 175, 100 120 Z`;

    return (
      <svg viewBox="0 0 400 240" className="w-full h-auto max-h-[280px]">
        {/* Cleavage Cytoplasm body */}
        <path
          d={pathD}
          fill="url(#cell-grad)"
          stroke="#10b981"
          strokeWidth="2.5"
          className="transition-all duration-100"
        />

        {/* Spindle poles (Centrioles) appearing after 25% */}
        {p > 0.2 && (
          <g className="opacity-80">
            {/* Left Centriole */}
            <circle cx={130} cy={120} r="4" fill="#6366f1" />
            {/* Right Centriole */}
            <circle cx={270} cy={120} r="4" fill="#6366f1" />
          </g>
        )}

        {/* Spindle Fibers pulling */}
        {p > 0.35 && p < 0.9 && (
          <g stroke="#818cf8" strokeWidth="0.5" strokeDasharray="2,2" className="opacity-60">
            {/* Spindles left */}
            <line x1={130} y1={120} x2={165 + p * 15} y2={95} />
            <line x1={130} y1={120} x2={165 + p * 15} y2={145} />
            {/* Spindles right */}
            <line x1={270} y1={120} x2={235 - p * 15} y2={95} />
            <line x1={270} y1={120} x2={235 - p * 15} y2={145} />
          </g>
        )}

        {/* Chromosomes details depending on phases */}
        {p < 0.25 && (
          // Interphase: Intact nucleus containing wool-like chromatin threads
          <g>
            <circle cx={200} cy={120} r="28" fill="#1e293b" stroke="#34d399" strokeWidth="1.5" strokeDasharray="3,3" />
            <path d="M 190 110 Q 200 130, 210 115 T 195 130" stroke="#f43f5e" strokeWidth="1" fill="none" className="opacity-50" />
            <path d="M 195 115 Q 185 125, 205 128 T 190 120" stroke="#60a5fa" strokeWidth="1" fill="none" className="opacity-50" />
          </g>
        )}

        {p >= 0.25 && p < 0.45 && (
          // Prophase: Condensed chromosomes random
          <g>
            {/* Chromosome X blobs */}
            <path d="M 180 100 L 195 115 M 195 100 L 180 115" stroke="#ec4899" strokeWidth="3" strokeLinecap="round" />
            <path d="M 210 125 L 225 140 M 225 125 L 210 140" stroke="#3b82f6" strokeWidth="3" strokeLinecap="round" />
          </g>
        )}

        {p >= 0.45 && p < 0.65 && (
          // Metaphase: Chromosomes aligned equatorially
          <g>
            <line x1={200} y1={80} x2={200} y2={160} stroke="rgba(244,63,94,0.3)" strokeWidth="1" strokeDasharray="3,3" />
            {/* Centered lining up chromosomes */}
            <path d="M 193 90 L 207 100 M 207 90 L 193 100" stroke="#ec4899" strokeWidth="3" strokeLinecap="round" />
            <path d="M 193 115 L 207 125 M 207 115 L 193 125" stroke="#3b82f6" strokeWidth="3" strokeLinecap="round" />
            <path d="M 193 140 L 207 150 M 207 140 L 193 150" stroke="#8b5cf6" strokeWidth="3" strokeLinecap="round" />
          </g>
        )}

        {p >= 0.65 && p < 0.9 && (
          // Anaphase: Pulled chromatids split
          <g>
            {/* Pulled Left */}
            <path d="M 165 95 L 155 90 M 165 95 L 155 102 M 165 135 L 155 130 M 165 135 L 155 142" stroke="#ec4899" strokeWidth="3" strokeLinecap="round" />
            {/* Pulled Right */}
            <path d="M 235 95 L 245 90 M 235 95 L 245 102 M 235 135 L 245 130 M 235 135 L 245 142" stroke="#3b82f6" strokeWidth="3" strokeLinecap="round" />
          </g>
        )}

        {p >= 0.9 && (
          // Telophase: 2 separate nuclei reforming
          <g>
            {/* Left Nucleolus */}
            <circle cx={145} cy={120} r="20" fill="#020617" stroke="#10b981" strokeWidth="1.5" />
            <path d="M 140 115 Q 145 125, 150 118" stroke="#ec4899" strokeWidth="1.5" fill="none" />
            {/* Right Nucleolus */}
            <circle cx={255} cy={120} r="20" fill="#020617" stroke="#10b981" strokeWidth="1.5" />
            <path d="M 250 115 Q 255 125, 260 118" stroke="#3b82f6" strokeWidth="1.5" fill="none" />
          </g>
        )}

        <defs>
          <linearGradient id="cell-grad" x1="0%" y1="0%" x2="100%" y2="100%">
            <stop offset="0%" stopColor="#10b981" stopOpacity="0.04" />
            <stop offset="100%" stopColor="#10b981" stopOpacity="0.18" />
          </linearGradient>
        </defs>
      </svg>
    );
  };

  // Render SVG for Carnot cycle indicator and piston moving
  const drawCarnot = () => {
    const p = progress / 100;
    
    // Cycle points A, B, C, D coordinates on Pressure-Volume grid
    // P-V graph starts at (80, 40) bottom is (200, 160)
    // A: high P, low V. B: high-mid P, med V. C: low P, high V. D: low-mid P, med-low V.
    const pts = {
      A: { x: 70, y: 50 },
      B: { x: 130, y: 75 },
      C: { x: 190, y: 150 },
      D: { x: 110, y: 135 }
    };

    // Interpolate current dot coordinates based on p
    let dotX = pts.A.x;
    let dotY = pts.A.y;
    let pistonY = 70; // piston expansion level
    let thermalColor = "rgba(100, 116, 139, 0.2)"; // plate heat color

    if (p < 0.25) {
      // Isothermal Expansion (A -> B)
      const ratio = p / 0.25;
      dotX = pts.A.x + (pts.B.x - pts.A.x) * ratio;
      dotY = pts.A.y + (pts.B.y - pts.A.y) * ratio;
      pistonY = 70 + ratio * 20;
      thermalColor = "rgba(239, 68, 68, 0.4)"; // Hot contact (Th)
    } else if (p < 0.5) {
      // Adiabatic Expansion (B -> C)
      const ratio = (p - 0.25) / 0.25;
      dotX = pts.B.x + (pts.C.x - pts.B.x) * ratio;
      dotY = pts.B.y + (pts.C.y - pts.B.y) * ratio;
      pistonY = 90 + ratio * 25;
      thermalColor = "rgba(100, 116, 139, 0.05)"; // Insulated (Q=0)
    } else if (p < 0.75) {
      // Isothermal Compression (C -> D)
      const ratio = (p - 0.5) / 0.25;
      dotX = pts.C.x + (pts.D.x - pts.C.x) * ratio;
      dotY = pts.C.y + (pts.D.y - pts.C.y) * ratio;
      pistonY = 115 - ratio * 30;
      thermalColor = "rgba(59, 130, 246, 0.4)"; // Cold sink (Tc)
    } else {
      // Adiabatic Compression (D -> A)
      const ratio = (p - 0.75) / 0.25;
      dotX = pts.D.x + (pts.A.x - pts.D.x) * ratio;
      dotY = pts.D.y + (pts.A.y - pts.D.y) * ratio;
      pistonY = 85 - ratio * 15;
      thermalColor = "rgba(100, 116, 139, 0.05)"; // Insulated (Q=0)
    }

    return (
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 items-center">
        {/* PV diagram SVG */}
        <div>
          <span className="text-[9px] font-black text-slate-500 uppercase tracking-wider block mb-1">
            PV Indicator Diagram
          </span>
          <svg viewBox="0 0 240 180" className="w-full bg-slate-950 rounded-xl border border-slate-900 overflow-visible p-2">
            {/* Grid Axes */}
            <line x1={40} y1={20} x2={40} y2={160} stroke="#475569" strokeWidth="1" />
            <line x1={40} y1={160} x2={220} y2={160} stroke="#475569" strokeWidth="1" />
            <text x={35} y={25} fill="#64748b" fontSize="8" textAnchor="end" fontWeight="bold">Pressure (P)</text>
            <text x={210} y={172} fill="#64748b" fontSize="8" textAnchor="middle" fontWeight="bold">Volume (V)</text>

            {/* Cycle curves (Bezier lines) */}
            {/* A -> B */}
            <path d={`M ${pts.A.x} ${pts.A.y} Q 100 62, ${pts.B.x} ${pts.B.y}`} stroke="#ef4444" strokeWidth="1.5" fill="none" />
            {/* B -> C */}
            <path d={`M ${pts.B.x} ${pts.B.y} Q 160 110, ${pts.C.x} ${pts.C.y}`} stroke="#f59e0b" strokeWidth="1.5" fill="none" />
            {/* C -> D */}
            <path d={`M ${pts.C.x} ${pts.C.y} Q 150 145, ${pts.D.x} ${pts.D.y}`} stroke="#3b82f6" strokeWidth="1.5" fill="none" />
            {/* D -> A */}
            <path d={`M ${pts.D.x} ${pts.D.y} Q 90 90, ${pts.A.x} ${pts.A.y}`} stroke="#a855f7" strokeWidth="1.5" fill="none" />

            {/* Stage point labels */}
            <text x={pts.A.x - 6} y={pts.A.y - 4} fill="#94a3b8" fontSize="8" fontWeight="bold">A</text>
            <text x={pts.B.x + 8} y={pts.B.y - 4} fill="#94a3b8" fontSize="8" fontWeight="bold">B</text>
            <text x={pts.C.x + 8} y={pts.C.y + 4} fill="#94a3b8" fontSize="8" fontWeight="bold">C</text>
            <text x={pts.D.x - 8} y={pts.D.y + 8} fill="#94a3b8" fontSize="8" fontWeight="bold">D</text>

            {/* Moving active state tracer */}
            <circle cx={dotX} cy={dotY} r="5" fill="#f59e0b" className="animate-pulse shadow-md" />
            <circle cx={dotX} cy={dotY} r="9" stroke="#f59e0b" strokeWidth="1" fill="none" className="animate-ping opacity-40" />
          </svg>
        </div>

        {/* Cylinder piston animation */}
        <div className="flex flex-col items-center">
          <span className="text-[9px] font-black text-slate-500 uppercase tracking-wider block mb-1">
            Gas Cylinder Assembly
          </span>
          <svg viewBox="0 0 160 180" className="w-40 bg-slate-950 rounded-xl border border-slate-900 overflow-visible">
            {/* Thermic interface block at the bottom */}
            <rect x={20} y={150} width={120} height={18} rx="3" fill={thermalColor} stroke="#334155" strokeWidth="1" className="transition-all duration-300" />
            <text x={80} y={162} fill="#94a3b8" fontSize="8" textAnchor="middle" fontWeight="bold" className="uppercase tracking-wider">
              {p < 0.25 ? "Hot Plate" : p >= 0.5 && p < 0.75 ? "Cold Sink" : "Insulation"}
            </text>

            {/* Cylinder boundary */}
            <rect x={35} y={30} width={90} height={120} fill="transparent" stroke="#475569" strokeWidth="2.5" />

            {/* Compressed / Expanded working fluid molecules */}
            <g opacity="0.6">
              {Array.from({ length: 15 }).map((_, i) => {
                // Scatter gas molecules inside the dynamic volume
                const stepSeed = Math.sin(i * 1.7) * 45;
                const cosSeed = Math.cos(i * 2.3) * 45;
                const atomX = 80 + stepSeed * 0.7;
                // Bound on top by the moving piston
                const volumeHeight = 150 - pistonY;
                const atomY = pistonY + 5 + Math.abs(cosSeed) * (volumeHeight / 55);

                return (
                  <circle
                    key={i}
                    cx={atomX}
                    cy={atomY}
                    r="2.5"
                    fill={p < 0.25 ? "#f87171" : p >= 0.5 && p < 0.75 ? "#60a5fa" : "#e2e8f0"}
                    className="transition-colors duration-300"
                  />
                );
              })}
            </g>

            {/* Piston head line and rod moving */}
            {/* Piston block */}
            <rect x={37} y={pistonY} width={86} height={10} fill="#64748b" stroke="#94a3b8" strokeWidth="1" />
            {/* Piston rod */}
            <rect x={76} y={10} width={8} height={pistonY - 10} fill="#cbd5e1" />
          </svg>
        </div>
      </div>
    );
  };

  // Render SVG for continuous customizable waves
  const drawWaves = () => {
    // Generate wave path using current freq and amp parameters
    const points: string[] = [];
    const width = 400;
    const height = 150;
    const centerY = height / 2;
    const t = progress * 0.25; // wave offset over time

    for (let x = 0; x <= width; x += 3) {
      // Calculate sine wave coordinates with parameter offsets
      const radians = (x * 0.05 * freq) - t;
      const y = centerY + Math.sin(radians) * amp;
      points.push(`${x},${y}`);
    }

    const pathD = `M ${points.join(' L ')}`;

    return (
      <div className="space-y-4">
        {/* Dynamic Wave display canvas */}
        <svg viewBox={`0 0 ${width} ${height}`} className="w-full bg-slate-950 rounded-xl border border-slate-900 overflow-hidden">
          {/* Axis center line */}
          <line x1={0} y1={centerY} x2={width} y2={centerY} stroke="#334155" strokeWidth="0.5" strokeDasharray="5,5" />
          
          {/* Active oscillating sine wave */}
          <path
            d={pathD}
            fill="none"
            stroke="url(#wave-grad)"
            strokeWidth="3.5"
            strokeLinecap="round"
            className="drop-shadow-[0_0_10px_rgba(59,130,246,0.5)]"
          />

          {/* Source node moving vertically */}
          <circle cx={4} cy={centerY + Math.sin(-t) * amp} r="6" fill="#f59e0b" />

          {/* Gradients */}
          <defs>
            <linearGradient id="wave-grad" x1="0" y1="0" x2="1" y2="0">
              <stop offset="0%" stopColor="#3b82f6" />
              <stop offset="50%" stopColor="#a855f7" />
              <stop offset="100%" stopColor="#ec4899" />
            </linearGradient>
          </defs>
        </svg>

        {/* Live numerical parameters box */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 bg-slate-950/60 p-4 border border-slate-850 rounded-xl">
          <div className="space-y-1.5">
            <div className="flex items-center justify-between text-[11px] font-bold text-slate-400">
              <span className="uppercase tracking-wider">Wave Frequency (f)</span>
              <span className="text-blue-400">{freq.toFixed(1)} Hz</span>
            </div>
            <input
              type="range"
              min="0.5"
              max="4.0"
              step="0.1"
              value={freq}
              onChange={(e) => setFreq(parseFloat(e.target.value))}
              className="w-full accent-blue-500 h-1 bg-slate-900 rounded-lg appearance-none cursor-pointer"
            />
          </div>

          <div className="space-y-1.5">
            <div className="flex items-center justify-between text-[11px] font-bold text-slate-400">
              <span className="uppercase tracking-wider">Amplitude (A)</span>
              <span className="text-purple-400">{amp.toFixed(0)} px</span>
            </div>
            <input
              type="range"
              min="5"
              max="65"
              value={amp}
              onChange={(e) => setAmp(parseInt(e.target.value))}
              className="w-full accent-purple-500 h-1 bg-slate-900 rounded-lg appearance-none cursor-pointer"
            />
          </div>
        </div>
      </div>
    );
  };

  // Render SVG for wave optics Double-Slit Diffraction
  const drawDoubleSlit = () => {
    // Wavelength color mapping (for screen readout and glowing source lines)
    const getWavelengthColor = (nm: number) => {
      if (nm < 450) return "#8b5cf6"; // Violet
      if (nm < 490) return "#06b6d4"; // Cyan
      if (nm < 560) return "#10b981"; // Green
      if (nm < 590) return "#eab308"; // Yellow
      if (nm < 630) return "#f97316"; // Orange
      return "#ef4444"; // Red
    };

    const laserColor = getWavelengthColor(wavelength);
    const p = progress / 100;

    return (
      <div className="space-y-4">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4 items-center">
          
          {/* Main propagation block (3 cols) */}
          <div className="md:col-span-3 relative h-40 bg-slate-950 rounded-xl border border-slate-900 overflow-hidden">
            {/* Slit Partition Wall */}
            <rect x={140} y={0} width={10} height={60} fill="#1e293b" stroke="#334155" strokeWidth="0.5" />
            <rect x={140} y={75} width={10} height={25} fill="#1e293b" stroke="#334155" strokeWidth="0.5" />
            <rect x={140} y={115} width={10} height={50} fill="#1e293b" stroke="#334155" strokeWidth="0.5" />

            {/* Incoming coherent plane wavefronts (before slits at x=140) */}
            {Array.from({ length: 5 }).map((_, i) => {
              // Scroll wavefronts right
              const xCoord = ((i * 30 + p * 30) % 140);
              return (
                <line
                  key={i}
                  x1={xCoord}
                  y1={0}
                  x2={xCoord}
                  y2={160}
                  stroke={laserColor}
                  strokeWidth="2"
                  strokeOpacity={Math.max(0, 1 - xCoord / 130)}
                />
              );
            })}

            {/* Slits positions: Slit1 (y=67), Slit2 (y=107) */}
            {/* Diffracted circular wavefronts radiating from the two slits */}
            {p > 0.1 && (
              <g stroke={laserColor} strokeWidth="1.5" fill="none">
                {Array.from({ length: 4 }).map((_, i) => {
                  const r = (i * 35 + p * 35) % 150;
                  if (r < 10) return null;
                  return (
                    <g key={i} strokeOpacity={Math.max(0, 1 - r / 140)}>
                      {/* Radiating from upper slit */}
                      <path d={`M 150 ${67 - r} A ${r} ${r} 0 0 1 150 ${67 + r}`} />
                      {/* Radiating from lower slit */}
                      <path d={`M 150 ${107 - r} A ${r} ${r} 0 0 1 150 ${107 + r}`} />
                    </g>
                  );
                })}
              </g>
            )}

            {/* Interference Screen at x=280 */}
            <line x1={290} y1={0} x2={290} y2={160} stroke="#475569" strokeWidth="3" />
          </div>

          {/* Detector Screen fringe representation (1 col) */}
          <div className="md:col-span-1 flex flex-col items-center justify-center p-3 bg-slate-950 rounded-xl border border-slate-900">
            <span className="text-[9px] font-black text-slate-500 uppercase tracking-wider block mb-2 text-center">
              Fringe Intensity Detector
            </span>
            <div className="w-full h-32 rounded bg-slate-950 flex flex-col overflow-hidden relative">
              {/* Overlapping bright and dark bands based on wavelength diffraction spacing */}
              {Array.from({ length: 11 }).map((_, i) => {
                // Calculate sinusoidal fringe intensity
                // Screen height is 128px, center is i=5
                const distFromCenter = Math.abs(i - 5);
                const slitSpacingFactor = 1.3;
                const fringeIntensity = Math.abs(Math.cos(distFromCenter * (wavelength / 180) * slitSpacingFactor));
                
                return (
                  <div
                    key={i}
                    className="flex-1 transition-all duration-300"
                    style={{
                      backgroundColor: laserColor,
                      opacity: fringeIntensity * (1 - distFromCenter * 0.15)
                    }}
                  />
                );
              })}
            </div>
          </div>
        </div>

        {/* Wavelength parameters controls */}
        <div className="space-y-1.5 bg-slate-950/60 p-4 border border-slate-850 rounded-xl">
          <div className="flex items-center justify-between text-[11px] font-bold text-slate-400">
            <span className="uppercase tracking-wider">Source Laser Wavelength (λ)</span>
            <span style={{ color: laserColor }} className="font-extrabold">{wavelength} nm</span>
          </div>
          <input
            type="range"
            min="400"
            max="700"
            step="10"
            value={wavelength}
            onChange={(e) => setWavelength(parseInt(e.target.value))}
            className="w-full h-1 bg-slate-900 rounded-lg appearance-none cursor-pointer"
            style={{ accentColor: laserColor }}
          />
        </div>
      </div>
    );
  };

  // Render SVG for Enzyme active-site mechanism
  const drawEnzyme = () => {
    const p = progress / 100;

    // Substrate Coordinates: moving from right to active site
    // At p=0: floating on the right. At p=0.5: bound into enzyme pocket. At p=1: split into two product pieces on the left
    let sub1X = 280;
    let sub1Y = 120;
    let sub2X = 280;
    let sub2Y = 100;
    let enzymeGlow = "rgba(16,185,129,0)";

    if (p < 0.5) {
      // Substrate approaching (280 -> 180)
      const ratio = p / 0.5;
      sub1X = 280 - ratio * 100;
      sub2X = 280 - ratio * 100;
      sub1Y = 115 - ratio * 5;
      sub2Y = 85 + ratio * 5;
    } else if (p < 0.65) {
      // Bound Enzyme-Substrate Complex (Glow increases)
      sub1X = 180;
      sub2X = 180;
      sub1Y = 110;
      sub2Y = 90;
      const ratio = (p - 0.5) / 0.15;
      enzymeGlow = `rgba(16,185,129,${ratio * 0.45})`;
    } else {
      // Splitting & Product Release (180 -> 80) and floating left separately
      const ratio = (p - 0.65) / 0.35;
      sub1X = 180 - ratio * 110;
      sub2X = 180 - ratio * 110;
      sub1Y = 110 + ratio * 45;
      sub2Y = 90 - ratio * 45;
      enzymeGlow = `rgba(16,185,129,${Math.max(0, 0.45 - ratio * 0.45)})`;
    }

    return (
      <svg viewBox="0 0 400 220" className="w-full h-auto max-h-[260px] bg-slate-950/20 border border-slate-900 rounded-2xl overflow-visible p-2">
        <defs>
          <filter id="active-glow" x="-20%" y="-20%" width="140%" height="140%">
            <feGaussianBlur stdDeviation="6" result="blur" />
            <feComposite in="SourceGraphic" in2="blur" operator="over" />
          </filter>
        </defs>

        {/* Glowing Enzyme backdrop active zone */}
        <circle cx={170} cy={110} r="45" fill={enzymeGlow} filter="url(#active-glow)" className="transition-all duration-300" />

        {/* Large Enzyme structure (Pac-man key shape) */}
        {/* Active site cleft: a rectangular/triangular indentation at x=170 to x=190, y=80 to y=140 */}
        <path
          d="M 120 110 C 120 60, 170 50, 170 80 Q 170 95, 185 95 Q 170 110, 185 110 Q 170 125, 185 125 Q 170 140, 170 140 C 170 170, 120 160, 120 110 Z"
          fill="#1e1b4b"
          stroke="#818cf8"
          strokeWidth="3"
        />
        <text x={140} y={114} fill="#818cf8" fontSize="10" fontWeight="900" textAnchor="middle" className="uppercase tracking-widest">Enzyme</text>

        {/* Reacting Substrate / Released pieces */}
        {p < 0.65 ? (
          // Single bound substrate (2 connecting interlocking parts)
          <g>
            <path
              d={`M ${sub1X} ${sub2Y} L ${sub1X + 15} ${sub2Y} L ${sub1X + 15} ${sub1Y + 15} L ${sub1X} ${sub1Y + 15} Q ${sub1X - 8} ${sub1Y + 5}, ${sub1X} ${sub2Y} Z`}
              fill="#ec4899"
              stroke="#f472b6"
              strokeWidth="1.5"
            />
            <text x={sub1X + 8} y={(sub1Y + sub2Y) / 2 + 4} fill="#ffffff" fontSize="7" fontWeight="bold" textAnchor="middle">Substrate</text>
          </g>
        ) : (
          // Two separate split product blocks floating off to the left
          <g>
            {/* Product piece 1 (Top) */}
            <path
              d={`M ${sub2X} ${sub2Y} L ${sub2X + 15} ${sub2Y} L ${sub2X + 15} ${sub2Y + 18} L ${sub2X} ${sub2Y + 18} Z`}
              fill="#fb7185"
              stroke="#fda4af"
              strokeWidth="1.5"
            />
            <text x={sub2X + 7} y={sub2Y + 12} fill="#ffffff" fontSize="6" fontWeight="bold" textAnchor="middle">P1</text>

            {/* Product piece 2 (Bottom) */}
            <path
              d={`M ${sub1X} ${sub1Y} L ${sub1X + 15} ${sub1Y} L ${sub1X + 15} ${sub1Y + 18} L ${sub1X} ${sub1Y + 18} Z`}
              fill="#38bdf8"
              stroke="#7dd3fc"
              strokeWidth="1.5"
            />
            <text x={sub1X + 7} y={sub1Y + 12} fill="#ffffff" fontSize="6" fontWeight="bold" textAnchor="middle">P2</text>
          </g>
        )}
      </svg>
    );
  };

  // Switch renderer depending on simulation preset
  const renderSpecimenCanvas = () => {
    switch (activePreset.id) {
      case "mitosis":
        return drawMitosis();
      case "carnot":
        return drawCarnot();
      case "waves":
        return drawWaves();
      case "doubleslit":
        return drawDoubleSlit();
      case "enzyme":
        return drawEnzyme();
      default:
        return null;
    }
  };

  return (
    <div className="my-8 rounded-3xl overflow-hidden border border-slate-800/80 bg-slate-950/40 backdrop-blur-xl shadow-2xl p-6 sm:p-8">
      {/* Simulation Header with Presets Toggle */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-850/80 pb-5 mb-5">
        <div>
          <h4 className="text-sm font-black text-slate-100 uppercase tracking-widest flex items-center gap-2">
            <Activity className="w-4 h-4 text-emerald-400 shrink-0" />
            <span>Interactive Dynamic Simulator</span>
          </h4>
          <p className="text-[11px] text-slate-400 font-semibold mt-1">
            Play, pause or manually scrub the timeline to study step-by-step states.
          </p>
        </div>

        {/* Switch presets pill navigation */}
        <div className="flex flex-wrap gap-1.5">
          {PRESETS.map((p) => (
            <button
              key={p.id}
              onClick={() => {
                setActivePreset(p);
                setProgress(0);
                setIsPlaying(false);
              }}
              className={`px-3 py-1.5 rounded-xl text-[10px] font-black uppercase tracking-wider transition-all cursor-pointer border ${
                activePreset.id === p.id
                  ? "bg-emerald-500/10 border-emerald-500/30 text-emerald-400 shadow-[0_0_12px_rgba(16,185,129,0.15)]"
                  : "bg-slate-900/60 border-slate-800/80 text-slate-400 hover:text-slate-200"
              }`}
            >
              {p.name.split(' ')[0]} {/* short descriptor */}
            </button>
          ))}
        </div>
      </div>

      {/* Main active speciment display */}
      <div className="bg-slate-950/80 rounded-2xl border border-slate-900 p-5 min-h-[220px] flex items-center justify-center">
        <div className="w-full">
          {renderSpecimenCanvas()}
        </div>
      </div>

      {/* Control center panel HUD with timeline scrubber and description */}
      <div className="mt-5 space-y-4 pt-4 border-t border-slate-850/80">
        
        {/* Scrubber Playback row */}
        <div className="flex flex-col sm:flex-row items-center gap-4">
          <div className="flex items-center gap-2.5">
            {/* Play/Pause Trigger */}
            <button
              onClick={() => setIsPlaying(!isPlaying)}
              className="p-3 bg-emerald-600 hover:bg-emerald-500 text-white rounded-xl transition-all cursor-pointer shadow-lg flex items-center justify-center"
            >
              {isPlaying ? <Pause className="w-4 h-4" /> : <Play className="w-4 h-4 pl-0.5" />}
            </button>

            {/* Reset timeline */}
            <button
              onClick={() => {
                setIsPlaying(false);
                setProgress(0);
              }}
              className="p-3 bg-slate-900 border border-slate-800 text-slate-400 hover:text-white rounded-xl transition-all cursor-pointer"
              title="Reset Timeline"
            >
              <RotateCcw className="w-4 h-4" />
            </button>
          </div>

          {/* Timeline scrubber progress input */}
          <div className="flex-1 w-full flex items-center gap-3">
            <span className="text-[10px] font-black text-slate-500 w-8 text-right font-mono">
              {Math.floor(progress)}%
            </span>
            <input
              type="range"
              min="0"
              max="100"
              step="1"
              value={progress}
              onChange={(e) => {
                setIsPlaying(false);
                setProgress(parseInt(e.target.value));
              }}
              className="flex-1 h-1.5 bg-slate-900 accent-emerald-400 rounded-lg appearance-none cursor-pointer"
            />
            <span className="text-[10px] font-black text-slate-500 w-8 font-mono">
              100%
            </span>
          </div>
        </div>

        {/* Step-by-Step Didactic readout description block */}
        <div className="bg-slate-900/30 border border-slate-850 rounded-2xl p-4 flex items-start gap-3">
          <div className="p-1.5 rounded-lg bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 mt-0.5">
            <Info className="w-4 h-4" />
          </div>
          <div className="space-y-1">
            <span className="text-[10px] font-black uppercase text-emerald-400 tracking-wider">
              {activeStage.label}
            </span>
            <p className="text-xs sm:text-sm text-slate-300 leading-relaxed font-semibold">
              {activeStage.details}
            </p>
          </div>
        </div>

      </div>
    </div>
  );
};
