"use client";

import React, { useState } from 'react';
import { Download, ChevronDown, FileText, Code, Box, Printer, Brain } from 'lucide-react';

interface ExportLessonButtonProps {
  title: string;
  subject: string;
  level: string;
  content: string;
  lang: string;
  courseSlug?: string;
  version?: string;
}

export const ExportLessonButton = ({ title, subject, level, content, lang, courseSlug, version }: ExportLessonButtonProps) => {
  const [dropdownOpen, setDropdownOpen] = useState(false);

  const getExportFilename = (suffix: string, ext: string) => {
    const cleanLevel = level.toUpperCase().replace(/[^A-Z0-9]+/g, '');
    const cleanSubject = subject.replace(/[^a-zA-Z0-9]+/g, '_');
    const cleanCourse = (courseSlug || '').replace(/[^a-zA-Z0-9]+/g, '_');
    const cleanChapter = title.toLowerCase().replace(/[^a-z0-9]+/g, '_');
    
    let parts = [cleanLevel, cleanSubject];
    if (cleanCourse) parts.push(cleanCourse);
    parts.push(cleanChapter);
    
    if (version) {
      let cleanVer = version.trim().toLowerCase().replace(/[^a-z0-9_.]/g, '');
      if (cleanVer.startsWith('v')) {
        cleanVer = cleanVer.substring(1);
      }
      cleanVer = cleanVer.replace(/\./g, '_');
      if (cleanVer) {
        parts.push(`v${cleanVer}`);
      }
    }
    
    if (suffix) {
      parts.push(suffix);
    }
    
    return `${parts.filter(Boolean).join('_')}.${ext}`;
  };

  const t = {
    export: lang === 'fr' ? 'Exporter' : 'Export',
    markdown: lang === 'fr' ? 'Markdown (.md)' : 'Markdown (.md)',
    json: lang === 'fr' ? 'Données JSON (.json)' : 'Structured JSON (.json)',
    scorm: lang === 'fr' ? 'Package SCORM (.zip)' : 'SCORM Package (.zip)',
    print: lang === 'fr' ? 'Impression HTML (.html)' : 'Printable HTML (.html)',
    revision: lang === 'fr' ? 'Fiche de Révision (.md)' : 'Revision Sheet (.md)'
  };

  const handleExportRevisionSheet = () => {
    const filename = getExportFilename('revision', 'md');
    
    // Parse Glossary terms
    const glossaryTerms: { term: string; definition: string }[] = [];
    const termRegex = /<Glossary\s+term="([^"]+)"\s+definition="([^"]+)"/g;
    let match: RegExpExecArray | null = null;
    while (true) {
      match = termRegex.exec(content);
      if (!match) break;
      const term = match[1];
      const definition = match[2];
      if (!glossaryTerms.some(item => item.term === term)) {
        glossaryTerms.push({ term, definition });
      }
    }

    // Build Mindmap Mermaid structure
    let mermaidMindmap = `mindmap\n  root((${title}))\n`;
    if (glossaryTerms.length > 0) {
      mermaidMindmap += `    Glossaire\n`;
      glossaryTerms.forEach(item => {
        const cleanTerm = item.term.replace(/[^a-zA-Z0-9 ]/g, '');
        mermaidMindmap += `      ${cleanTerm}\n`;
      });
    }

    const revisionContent = `# ${lang === 'fr' ? 'Fiche de Révision' : 'Revision Sheet'} : ${title}
**${lang === 'fr' ? 'Discipline' : 'Subject'} :** ${subject} • **${lang === 'fr' ? 'Niveau' : 'Level'} :** ${level}
**${lang === 'fr' ? 'Généré le' : 'Generated on'} :** ${new Date().toLocaleDateString()}

## 🗺️ ${lang === 'fr' ? 'Carte Mentale (MindMap)' : 'MindMap (Concept Graph)'}
\`\`\`mermaid
${mermaidMindmap}\`\`\`

## 📚 ${lang === 'fr' ? 'Glossaire des Notions Clés' : 'Key Concepts Glossary'}
${glossaryTerms.map(item => `* **${item.term}** : ${item.definition}`).join('\n')}

---
*Generated by OpenPrimer*`;

    const blob = new Blob([revisionContent], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
    setDropdownOpen(false);
  };

  const handleExportMarkdown = () => {
    const filename = getExportFilename('', 'md');
    const frontmatter = `---
title: "${title}"
subject: "${subject}"
level: "${level}"
lang: "${lang}"
---

${content}`;
    
    const blob = new Blob([frontmatter], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
    setDropdownOpen(false);
  };

  const handleExportJson = () => {
    const filename = getExportFilename('', 'json');
    const data = {
      title,
      subject,
      level,
      lang,
      exportedAt: new Date().toISOString(),
      format: "OpenPrimer course export",
      content
    };
    
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
    setDropdownOpen(false);
  };

  const handleExportHtml = () => {
    const filename = getExportFilename('', 'html');
    const htmlContent = `<!DOCTYPE html>
<html lang="${lang}">
<head>
  <meta charset="UTF-8">
  <title>${title}</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
      line-height: 1.6;
      color: #334155;
      max-width: 800px;
      margin: 40px auto;
      padding: 0 20px;
    }
    h1 { font-size: 2.5rem; font-weight: 800; color: #0f172a; margin-bottom: 20px; }
    h2 { font-size: 1.75rem; font-weight: 700; color: #1e293b; margin-top: 40px; border-bottom: 1px solid #e2e8f0; padding-bottom: 10px; }
    h3 { font-size: 1.25rem; font-weight: 600; color: #334155; }
    p { margin-bottom: 20px; }
    blockquote {
      border-left: 4px solid #3b82f6;
      background-color: #f8fafc;
      padding: 15px 20px;
      margin: 20px 0;
      border-radius: 0 8px 8px 0;
    }
    code { background: #f1f5f9; padding: 2px 6px; border-radius: 4px; font-family: monospace; font-size: 0.9em; }
    pre { background: #1e293b; color: #f8fafc; padding: 20px; border-radius: 8px; overflow-x: auto; }
    pre code { background: none; padding: 0; color: inherit; }
  </style>
</head>
<body>
  <header>
    <p style="text-transform: uppercase; font-size: 0.8rem; font-weight: bold; letter-spacing: 0.1em; color: #64748b;">${subject} &bull; ${level}</p>
    <h1>${title}</h1>
  </header>
  <main>
    ${content.replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\n/g, "<br/>")}
  </main>
</body>
</html>`;

    const blob = new Blob([htmlContent], { type: 'text/html;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
    setDropdownOpen(false);
  };

  const handleExportScorm = () => {
    const filename = getExportFilename('scorm', 'zip');
    
    const imsManifestXml = `<?xml version="1.0" encoding="UTF-8"?>
<manifest identifier="OpenPrimer_SCORM_Course" version="1.1"
          xmlns="http://www.imsproject.org/xsd/imscp_rootv1p1p2"
          xmlns:adlcp="http://www.adlnet.org/xsd/adlcp_v1p3"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.imsproject.org/xsd/imscp_rootv1p1p2 imscp_rootv1p1p2.xsd
                              http://www.adlnet.org/xsd/adlcp_v1p3 adlcp_v1p3.xsd">
  <metadata>
    <schema>ADL SCORM</schema>
    <schemaversion>1.2</schemaversion>
  </metadata>
  <organizations default="openprimer_org">
    <organization identifier="openprimer_org">
      <title>${title}</title>
      <item identifier="item_1" identifierref="resource_1">
        <title>${title}</title>
      </item>
    </organization>
  </organizations>
  <resources>
    <resource identifier="resource_1" type="webcontent" adlcp:scormtype="sco" href="index.html">
      <file href="index.html" />
    </resource>
  </resources>
</manifest>`;

    const indexHtml = `<!DOCTYPE html>
<html lang="${lang}">
<head>
  <meta charset="UTF-8">
  <title>${title}</title>
  <style>
    body {
      font-family: system-ui, -apple-system, sans-serif;
      line-height: 1.6;
      color: #334155;
      max-width: 800px;
      margin: 40px auto;
      padding: 0 20px;
    }
  </style>
</head>
<body>
  <h1>${title}</h1>
  <div>${content.replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\n/g, "<br/>")}</div>
</body>
</html>`;

    // Package as ZIP client-side
    const files = [
      { name: "imsmanifest.xml", content: imsManifestXml },
      { name: "index.html", content: indexHtml }
    ];

    const zipBlob = generateSimpleZip(files);
    const url = URL.createObjectURL(zipBlob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
    setDropdownOpen(false);
  };

  // Minimal ZIP packaging utility
  const generateSimpleZip = (files: { name: string; content: string }[]) => {
    const encoder = new TextEncoder();
    const fileDataList: any[] = [];
    let currentOffset = 0;
    const localHeaders: Uint8Array[] = [];

    for (const f of files) {
      const nameBytes = encoder.encode(f.name);
      const contentBytes = encoder.encode(f.content);
      
      const header = new Uint8Array(30 + nameBytes.length);
      const view = new DataView(header.buffer);
      
      view.setUint32(0, 0x04034b50, true);
      view.setUint16(4, 10, true);
      view.setUint16(6, 0, true);
      view.setUint16(8, 0, true);
      view.setUint16(10, 0, true);
      view.setUint16(12, 0, true);
      
      let crc = 0xffffffff;
      for (let i = 0; i < contentBytes.length; i++) {
        crc ^= contentBytes[i];
        for (let j = 0; j < 8; j++) {
          crc = (crc >>> 1) ^ (crc & 1 ? 0xedb88320 : 0);
        }
      }
      crc ^= 0xffffffff;
      
      view.setUint32(14, crc, true);
      view.setUint32(18, contentBytes.length, true);
      view.setUint32(22, contentBytes.length, true);
      view.setUint16(26, nameBytes.length, true);
      view.setUint16(28, 0, true);
      
      header.set(nameBytes, 30);
      
      localHeaders.push(header);
      localHeaders.push(contentBytes);
      
      fileDataList.push({ nameBytes, contentBytes, offset: currentOffset });
      currentOffset += header.length + contentBytes.length;
    }

    const centralHeaders: Uint8Array[] = [];
    let centralDirectorySize = 0;
    for (const f of fileDataList) {
      const header = new Uint8Array(46 + f.nameBytes.length);
      const view = new DataView(header.buffer);
      
      view.setUint32(0, 0x02014b50, true);
      view.setUint16(4, 20, true);
      view.setUint16(6, 10, true);
      view.setUint16(8, 0, true);
      view.setUint16(10, 0, true);
      view.setUint16(12, 0, true);
      view.setUint16(14, 0, true);
      
      let crc = 0xffffffff;
      for (let i = 0; i < f.contentBytes.length; i++) {
        crc ^= f.contentBytes[i];
        for (let j = 0; j < 8; j++) {
          crc = (crc >>> 1) ^ (crc & 1 ? 0xedb88320 : 0);
        }
      }
      crc ^= 0xffffffff;
      
      view.setUint32(16, crc, true);
      view.setUint32(20, f.contentBytes.length, true);
      view.setUint32(24, f.contentBytes.length, true);
      view.setUint16(28, f.nameBytes.length, true);
      view.setUint16(30, 0, true);
      view.setUint16(32, 0, true);
      view.setUint16(34, 0, true);
      view.setUint16(36, 0, true);
      view.setUint32(38, 0, true);
      view.setUint32(42, f.offset, true);
      
      header.set(f.nameBytes, 46);
      centralHeaders.push(header);
      centralDirectorySize += header.length;
    }

    const eocd = new Uint8Array(22);
    const eocdView = new DataView(eocd.buffer);
    eocdView.setUint32(0, 0x06054b50, true);
    eocdView.setUint16(4, 0, true);
    eocdView.setUint16(6, 0, true);
    eocdView.setUint16(8, fileDataList.length, true);
    eocdView.setUint16(10, fileDataList.length, true);
    eocdView.setUint32(12, centralDirectorySize, true);
    eocdView.setUint32(16, currentOffset, true);
    eocdView.setUint16(20, 0, true);

    const blobs = [...localHeaders, ...centralHeaders, eocd];
    return new Blob(blobs as any[], { type: 'application/zip' });
  };

  return (
    <div className="relative inline-block text-left distraction-free-hide font-sans">
      <div>
        <button
          type="button"
          onClick={() => setDropdownOpen(!dropdownOpen)}
          className="inline-flex items-center gap-2 px-4 py-2 text-xs font-black uppercase tracking-widest bg-slate-900 hover:bg-slate-850 text-slate-300 hover:text-white border border-slate-800 rounded-xl transition-all cursor-pointer shadow-md select-none"
          id="export-menu-button"
          aria-expanded={dropdownOpen}
          aria-haspopup="true"
        >
          <Download className="w-3.5 h-3.5" />
          <span>{t.export}</span>
          <ChevronDown className="w-3 h-3 text-slate-500" />
        </button>
      </div>

      {dropdownOpen && (
        <>
          <div 
            onClick={() => setDropdownOpen(false)} 
            className="fixed inset-0 z-40"
          />
          <div className="absolute right-0 mt-2 w-56 rounded-2xl bg-slate-900 border border-slate-800 shadow-2xl ring-1 ring-black ring-opacity-5 focus:outline-none z-50 overflow-hidden divide-y divide-slate-800/40 animate-fade-in">
            <div className="py-1">
              <button
                onClick={handleExportRevisionSheet}
                className="w-full flex items-center gap-3 px-4 py-3 text-xs font-semibold text-slate-300 hover:text-white hover:bg-slate-850/50 transition-colors text-left cursor-pointer"
              >
                <Brain className="w-4 h-4 text-pink-400" />
                <span>{t.revision}</span>
              </button>
            </div>
            <div className="py-1">
              <button
                onClick={handleExportMarkdown}
                className="w-full flex items-center gap-3 px-4 py-3 text-xs font-semibold text-slate-300 hover:text-white hover:bg-slate-850/50 transition-colors text-left cursor-pointer"
              >
                <FileText className="w-4 h-4 text-blue-400" />
                <span>{t.markdown}</span>
              </button>
              <button
                onClick={handleExportJson}
                className="w-full flex items-center gap-3 px-4 py-3 text-xs font-semibold text-slate-300 hover:text-white hover:bg-slate-850/50 transition-colors text-left cursor-pointer"
              >
                <Code className="w-4 h-4 text-indigo-400" />
                <span>{t.json}</span>
              </button>
            </div>
            <div className="py-1">
              <button
                onClick={handleExportScorm}
                className="w-full flex items-center gap-3 px-4 py-3 text-xs font-semibold text-slate-300 hover:text-white hover:bg-slate-850/50 transition-colors text-left cursor-pointer"
              >
                <Box className="w-4 h-4 text-violet-400" />
                <span>{t.scorm}</span>
              </button>
              <button
                onClick={handleExportHtml}
                className="w-full flex items-center gap-3 px-4 py-3 text-xs font-semibold text-slate-300 hover:text-white hover:bg-slate-850/50 transition-colors text-left cursor-pointer"
              >
                <Printer className="w-4 h-4 text-emerald-400" />
                <span>{t.print}</span>
              </button>
            </div>
          </div>
        </>
      )}
    </div>
  );
};
