"use client";

import React, { useState, useEffect } from 'react';
import Link from 'next/link';
import { 
  Shield, Target, Users, Mail, Phone, MapPin, Globe, Sparkles, 
  BookOpen, ChevronRight, Search, Filter, Book, Award, Zap
} from 'lucide-react';
import { TopNav } from './RefinedUI';

const Footer = () => (
  <footer className="mt-32 pt-16 border-t border-slate-900 pb-12 px-8">
    <div className="max-w-5xl mx-auto text-center">
       <p className="text-[10px] font-black text-slate-800 uppercase tracking-[0.3em]">
         OpenPrimer Project • 2026 • Global AI Academic Initiative
       </p>
    </div>
  </footer>
);

// --- PAGE: MISSION ---
export const MissionPage = () => (
  <div className="min-h-screen bg-slate-950 text-white font-sans">
    <TopNav />
    <div className="max-w-4xl mx-auto px-8 pt-32 pb-24">
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="flex items-center gap-3 mb-8">
        <Target className="w-8 h-8 text-blue-500" />
        <h1 className="text-4xl font-black tracking-tighter">The OpenPrimer Mission</h1>
      </motion.div>
      
      <div className="space-y-12">
        <section>
          <h2 className="text-2xl font-bold mb-4 text-blue-400">Democratizing Elite Education</h2>
          <p className="text-lg text-slate-400 leading-relaxed">
            Our goal is to build a bridge between top-tier academic rigor and universal accessibility. 
            OpenPrimer uses the **Feynman Engine** to synthesize complex university-level concepts into 
            interactive, multi-language modules that anyone can master, regardless of their background.
          </p>
        </section>

        <div className="grid md:grid-cols-2 gap-8">
          <div className="p-8 bg-slate-900/40 border border-slate-800 rounded-3xl backdrop-blur-xl">
            <Zap className="w-8 h-8 text-yellow-500 mb-4" />
            <h3 className="font-bold mb-4 text-white uppercase tracking-widest text-xs">Active Recall</h3>
            <p className="text-sm text-slate-500">Every module is built with Solved Problems and active checkpoints to ensure deep retention.</p>
          </div>
          <div className="p-8 bg-slate-900/40 border border-slate-800 rounded-3xl backdrop-blur-xl">
            <Globe className="w-8 h-8 text-emerald-500 mb-4" />
            <h3 className="font-bold mb-4 text-white uppercase tracking-widest text-xs">Multilingual Core</h3>
            <p className="text-sm text-slate-500">Starting with the 5 most common global languages, our platform evolves JIT into secondary languages for absolute inclusivity.</p>
          </div>
        </div>
      </div>
    </div>
    <Footer />
  </div>
);

import { motion } from 'framer-motion';

// --- PAGE: CATALOG ---
export const CatalogPage = () => {
  const [filter, setFilter] = useState('All');
  const [searchQuery, setSearchQuery] = useState('');

  const courses = [
    { id: 1, title: "Kinematics 1D", level: "L1", subject: "Physics", tags: ["Mechanics", "EN", "FR"], slug: "kinematics-1d" },
    { id: 2, title: "Cell Structure", level: "L1", subject: "Biology", tags: ["Cellular", "EN", "ES"], slug: "cell-structure" },
    { id: 3, title: "Constitutional Law", level: "L1", subject: "Law", tags: ["Politics", "EN", "FR", "DE"], slug: "const-law" },
    { id: 4, title: "Linear Algebra", level: "L1", subject: "Mathematics", tags: ["Matrices", "EN", "PT"], slug: "linear-algebra" },
    { id: 5, title: "Quantum Basics", level: "L2", subject: "Physics", tags: ["Advanced", "EN"], slug: "quantum-basics" },
  ];

  const filteredCourses = courses.filter(c => 
    (filter === 'All' || c.subject === filter) &&
    (c.title.toLowerCase().includes(searchQuery.toLowerCase()) || c.subject.toLowerCase().includes(searchQuery.toLowerCase()))
  );

  return (
    <div className="min-h-screen bg-slate-950 text-white font-sans">
      <TopNav />
      <div className="max-w-6xl mx-auto px-8 pt-32 pb-24">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-8 mb-16">
          <div>
            <h1 className="text-5xl font-black tracking-tighter mb-4">Academic Catalog</h1>
            <p className="text-slate-500 font-medium">Explore modules generated by the Feynman Engine v1.5.</p>
          </div>
          
          <div className="flex flex-col gap-4">
            <div className="relative group">
              <Search className="absolute left-4 top-3.5 w-4 h-4 text-slate-600 group-focus-within:text-blue-500 transition-colors" />
              <input 
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder="Search modules..." 
                className="bg-slate-900 border border-slate-800 rounded-2xl py-3 pl-12 pr-6 text-sm focus:outline-none focus:border-blue-500/50 transition-all w-full md:w-80" 
              />
            </div>
            <div className="flex gap-2">
              {['All', 'Physics', 'Biology', 'Law', 'Mathematics'].map(cat => (
                <button 
                  key={cat}
                  onClick={() => setFilter(cat)}
                  className={`px-4 py-2 rounded-full border text-[10px] font-black uppercase tracking-widest transition-all ${filter === cat ? 'bg-blue-600 border-blue-500 text-white shadow-lg shadow-blue-600/20' : 'bg-slate-900 border-slate-800 text-slate-500 hover:border-slate-700'}`}
                >
                  {cat}
                </button>
              ))}
            </div>
          </div>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
          {filteredCourses.map((course) => (
            <motion.div 
              layout
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              key={course.id}
            >
              <Link href={`/${course.level}/${course.subject}/${course.slug}/introduction`} className="group block h-full">
                <div className="p-8 bg-slate-900/40 border border-slate-800/50 rounded-[40px] hover:border-blue-500/50 transition-all shadow-2xl hover:shadow-blue-600/10 flex flex-col h-full group-hover:bg-slate-900/60 backdrop-blur-xl">
                  <div className="flex justify-between items-start mb-6">
                    <div className="w-12 h-12 bg-blue-600/10 rounded-2xl flex items-center justify-center text-blue-400 group-hover:scale-110 transition-transform duration-500">
                      <Book className="w-6 h-6" />
                    </div>
                    <span className="bg-slate-950 px-3 py-1 rounded-full border border-slate-800 text-[9px] font-black uppercase tracking-widest text-slate-500">{course.level}</span>
                  </div>
                  
                  <h3 className="text-xl font-black mb-3 group-hover:text-blue-400 transition-colors">{course.title}</h3>
                  <p className="text-sm text-slate-500 mb-8 flex-1 leading-relaxed">
                    Advanced curriculum module covering key concepts in {course.subject} with active learning checkpoints.
                  </p>
                  
                  <div className="flex items-center justify-between pt-6 border-t border-slate-800/50">
                    <div className="flex gap-2">
                       {course.tags.map(tag => (
                         <span key={tag} className="text-[9px] font-bold text-slate-700">{tag}</span>
                       ))}
                    </div>
                    <ChevronRight className="w-5 h-5 text-slate-700 group-hover:text-blue-500 group-hover:translate-x-1 transition-all" />
                  </div>
                </div>
              </Link>
            </motion.div>
          ))}
        </div>
      </div>
      <Footer />
    </div>
  );
};

// --- PAGE: ABOUT ---
export const AboutPage = () => (
  <div className="min-h-screen bg-slate-950 text-white font-sans">
    <TopNav />
    <div className="max-w-4xl mx-auto px-8 pt-32 pb-24">
      <div className="flex items-center gap-3 mb-12">
        <Users className="w-8 h-8 text-emerald-500" />
        <h1 className="text-4xl font-black tracking-tighter">Who Are We?</h1>
      </div>
      <div className="prose prose-invert prose-slate max-w-none space-y-8 text-slate-400 leading-relaxed">
        <p className="text-lg">
          OpenPrimer is an international consortium of educators, AI engineers, and open-source advocates. 
          We believe that elite education should not be a luxury restricted to the few, but a fundamental 
          human right accessible in every language.
        </p>
        <div className="grid md:grid-cols-2 gap-12 mt-16">
          <div className="space-y-4">
             <div className="w-10 h-10 rounded-xl bg-blue-500/10 flex items-center justify-center text-blue-500">
               <Award className="w-5 h-5" />
             </div>
             <h3 className="font-bold text-white uppercase text-xs tracking-widest">Academic Excellence</h3>
             <p className="text-sm">Our generation engine is calibrated against top university syllabi to ensure factual accuracy and instructional depth.</p>
          </div>
          <div className="space-y-4">
             <div className="w-10 h-10 rounded-xl bg-emerald-500/10 flex items-center justify-center text-emerald-500">
               <Globe className="w-5 h-5" />
             </div>
             <h3 className="font-bold text-white uppercase text-xs tracking-widest">Global Reach</h3>
             <p className="text-sm">With native support for English, French, Spanish, German, and Portuguese, we cover 60% of the world's student population.</p>
          </div>
        </div>
      </div>
    </div>
    <Footer />
  </div>
);

// --- PAGE: CONTACT ---
export const ContactPage = () => (
  <div className="min-h-screen bg-slate-950 text-white font-sans">
    <TopNav />
    <div className="max-w-4xl mx-auto px-8 pt-32 pb-24">
      <div className="flex items-center gap-3 mb-12">
        <Mail className="w-8 h-8 text-violet-500" />
        <h1 className="text-4xl font-black tracking-tighter">Contact the Consortium</h1>
      </div>
      <div className="grid md:grid-cols-2 gap-12">
        <div className="space-y-12">
          <p className="text-slate-400 leading-relaxed">
            Spotted an error? Want to contribute to the Feynman Engine? Or interested in a partnership? 
            Reach out to our global team.
          </p>
          <div className="space-y-6">
            <div className="flex items-center gap-4 group cursor-pointer">
              <div className="w-12 h-12 bg-slate-900 border border-slate-800 rounded-2xl flex items-center justify-center text-slate-500 group-hover:text-blue-500 group-hover:border-blue-500/30 transition-all">
                <Mail className="w-5 h-5" />
              </div>
              <div>
                <p className="text-[10px] font-black text-slate-700 uppercase tracking-widest">Email Us</p>
                <p className="font-bold text-slate-200">global-ops@openprimer.org</p>
              </div>
            </div>
            <div className="flex items-center gap-4 group cursor-pointer">
              <div className="w-12 h-12 bg-slate-900 border border-slate-800 rounded-2xl flex items-center justify-center text-slate-500 group-hover:text-emerald-500 group-hover:border-emerald-500/30 transition-all">
                <Globe className="w-5 h-5" />
              </div>
              <div>
                <p className="text-[10px] font-black text-slate-700 uppercase tracking-widest">HQ Location</p>
                <p className="font-bold text-slate-200">Decentralized Consortium</p>
              </div>
            </div>
          </div>
        </div>
        
        <div className="bg-slate-900/50 p-10 rounded-[40px] border border-slate-800 shadow-2xl backdrop-blur-2xl">
           <form className="space-y-6" onSubmit={(e) => e.preventDefault()}>
              <div className="space-y-2">
                <label className="text-[10px] font-black text-slate-700 uppercase tracking-widest ml-1">Full Name</label>
                <input type="text" placeholder="John Doe" className="w-full bg-slate-950/50 border border-slate-800 rounded-2xl p-4 text-sm focus:outline-none focus:border-blue-500/50 transition-all" />
              </div>
              <div className="space-y-2">
                <label className="text-[10px] font-black text-slate-700 uppercase tracking-widest ml-1">Message</label>
                <textarea placeholder="How can we help?" className="w-full bg-slate-950/50 border border-slate-800 rounded-2xl p-4 text-sm h-40 focus:outline-none focus:border-blue-500/50 transition-all resize-none"></textarea>
              </div>
              <button className="w-full bg-blue-600 hover:bg-blue-500 text-white font-black uppercase tracking-widest text-[10px] py-5 rounded-2xl transition-all shadow-xl shadow-blue-600/20">
                Send Inquiry
              </button>
           </form>
        </div>
      </div>
    </div>
    <Footer />
  </div>
);
